a = input('digite algo: ')
print('O tipo desse valor é ', type(a))
print('Só tem espaco? ', a.isspace())
print('É numérico? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alphanumeric? ', a.isalnum())
print('É maiúsculo?  ', a.isupper())
print('É minusculo?  ', a.islower())
print('Ela está capitalizada? ', a.istitle())